| **Pattern**                        | **Description**                                                    | **Common Use Cases / Problems**                                                               | **Why It’s Powerful**                                                 |
| ---------------------------------- | ------------------------------------------------------------------ | --------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| **Two Pointers**                   | Maintain two indices to traverse array/string simultaneously.      | Two-sum (sorted), reverse array, move zeroes, container with most water                       | Reduces **O(n² → O(n))** in many problems                             |
| **Sliding Window**                 | Maintain a window (fixed or variable) and slide over array/string. | Max sum subarray size k, min subarray sum ≥ target, longest substring without repeating chars | Handles **contiguous subarray/subsequence problems** efficiently      |
| **Fast & Slow Pointers (Floyd’s)** | Use two pointers moving at different speeds.                       | Detect cycle in linked list, middle of list, linked list palindrome                           | Detect cycles and find middle points in **O(n)** without extra space  |
| **Prefix Sum / Cumulative Sum**    | Precompute sums for subarrays to answer sum queries fast.          | Subarray sum = k, range sum queries, 2D matrix sum queries                                    | Reduces repeated summation calculations **O(n² → O(n))**              |
| **Hashing**                        | Use hash maps/sets to track frequency or presence.                 | Two-sum, count duplicates, subarray sum k, longest substring unique                           | Enables **O(1) lookup**; avoids nested loops                          |
| **Recursion / Backtracking**       | Solve problems by exploring all possibilities recursively.         | N-Queens, sudoku, permutations, subsets                                                       | Handles **combinatorial/exploratory problems** elegantly              |
| **Dynamic Programming (DP)**       | Break problems into overlapping subproblems; store results.        | Fibonacci, knapsack, LIS, min coin change                                                     | Optimizes **exponential brute-force → polynomial time**               |
| **Binary Search**                  | Divide search space in half repeatedly.                            | Search in sorted array, find floor/ceil, rotated sorted array, allocation problems            | Reduces **O(n) → O(log n)**; works in arrays, monotonic functions     |
| **Greedy**                         | Make locally optimal choice hoping global optimum.                 | Interval scheduling, coin change (if denominations allow), minimum platforms                  | Fast, simple, works when problem satisfies **greedy-choice property** |
| **Monotonic Stack / Queue**        | Maintain increasing/decreasing stack or deque.                     | Next greater/smaller element, sliding window max/min                                          | Handles **range queries / comparisons efficiently**                   |
| **Union-Find (Disjoint Set)**      | Track connected components in a set.                               | Detect cycles, Kruskal MST, friend circles                                                    | Efficient for **connectivity problems in graphs**                     |
