| Rank | Problem / Component                   | LeetCode / Similar | Core Logic Summary                                    | Key Data Structures                            | Why Asked                        | Difficulty  |
| ---- | ------------------------------------- | ------------------ | ----------------------------------------------------- | ---------------------------------------------- | -------------------------------- | ----------- |
| 1    | LRU Cache                             | 146                | Move-to-front on access, evict least-recent when full | HashMap + Doubly Linked List                   | Classic caching; O(1) ops        | Medium      |
| 2    | LFU Cache                             | 460                | Evict least frequent; tie → least recent              | HashMap + freq → DoublyList + min-freq pointer | Harder LRU variant               | Hard        |
| 3    | Hit Counter                           | 362                | Record hits per timestamp; count last 5 min           | Queue OR fixed 300 buckets                     | Sliding time-window logic        | Medium      |
| 4    | Rate Limiter – Token Bucket           | —                  | Refill tokens at fixed rate; allow bursts             | Map<client, {tokens,lastRefill}>               | Standard for APIs; smooth bursts | Medium      |
| 5    | Sliding Window Counter                | —                  | Weighted sum of current + prev window                 | Map<client,{curr,prev,time}>                   | Balanced modern limiter          | Medium      |
| 6    | Fixed Window Counter                  | —                  | Count per bucket, reset each window                   | Map<client,{count,windowStart}>                | Simplest, boundary burst flaw    | Easy-Medium |
| 7    | Sliding Window Log                    | —                  | Keep timestamps deque; remove old                     | Map<client,Deque<Long>>                        | Exact sliding, memory-heavy      | Medium      |
| 8    | Top K Leaderboard                     | 1244 variant       | Update scores; get top K                              | HashMap + TreeMap/Heap                         | Real-time ranking                | Medium      |
| 9    | Time-based KV Store                   | 981                | Get value at timestamp                                | Map<key,List<(value,ts)>> + binary search      | Versioned data                   | Medium      |
| 10   | TTL / Sliding Expiry Cache            | —                  | Evict on expiry; refresh TTL                          | HashMap + PriorityQueue OR lazy check          | Real sessions; cache refresh     | Medium      |
| 11   | Retry w/ Exponential Backoff + Jitter | —                  | Wait = base × 2^attempt + random jitter               | Loop / math                                    | Reliability pattern              | Easy-Medium |
| 12   | Circuit Breaker                       | —                  | Closed → Open → Half-Open; track failures             | State enum + counters + timeout                | Prevent cascading failures       | Medium      |
| 13   | TinyURL w/ Rate Limiting              | 535 variant        | Shorten URL; handle collisions                        | HashMap + base62/counter                       | Hashing + collision + limiter    | Easy-Medium |
| 14   | Autocomplete w/ Frequency             | 642 / 1268         | Trie + top-K suggestions                              | Trie + Heap OR sorted list                     | Core search system               | Medium-Hard |
| 15   | Top K Frequent in Stream              | 347 / 692          | Maintain freq, keep top K                             | HashMap + MinHeap / buckets                    | Streaming analytics              | Medium      |
| 16   | Snake Game                            | 353                | Move, eat, grow, detect collisions                    | Deque + Set                                    | State + direction + queue        | Medium      |
| 17   | Vending Machine                       | —                  | Insert money, select item, dispense/change            | State machine + inventory + money              | Real-world transaction/state     | Medium      |
| 18   | Parking Lot                           | —                  | Entry/exit, spot allocation, payment                  | Arrays / Maps                                  | Resource allocation; OOP         | Easy-Medium |
| 19   | Elevator System                       | —                  | Request handling, direction optimization              | PriorityQueue + state                          | Event-driven scheduling          | Hard        |
| 20   | File System (Trie)                    | 1166 variant       | Create/delete/list files/folders                      | Trie (Map<String,Node>)                        | Hierarchical storage             | Medium      |
