| #  | Problem                                       | Technique / Type                          | Example                                                                | Notes / Use Case                                        |
| -- | --------------------------------------------- | ----------------------------------------- | ---------------------------------------------------------------------- | ------------------------------------------------------- |
| 1  | **4Sum**                                      | Four-pointer (Fix two + two-pointer scan) | `nums=[1,0,-1,0,-2,2], target=0 → [-2,-1,1,2], [-2,0,0,2], [-1,0,0,1]` | Classic LeetCode problem; extend 3Sum logic.            |
| 2  | **4Sum Closest**                              | Four-pointer                              | `[1,2,3,4,5], target=10 → sum closest=10`                              | Find quadruplet sum closest to target.                  |
| 3  | **Quadruplet with product = target**          | Sorting + Four-pointer                    | `[1,2,3,4,6], target=24 → [2,3,4,1]`                                   | Extension of 2-product / 3-product problems.            |
| 4  | **Count quadruplets with sum = target**       | Four-pointer                              | `[1,1,2,2,3], target=6 → count=2`                                      | Count number of quadruplets.                            |
| 5  | **Find ranges covering four elements**        | Four-pointer                              | `[1,3,5,6,7,9], targetRange=15 → [1,3,5,6]`                            | Find all ranges satisfying sum / difference conditions. |
| 6  | **Quadruplet sum divisible by K**             | Sorting + Four-pointer                    | `[1,2,3,4,5], K=3 → [1,2,3,6]`                                         | Product or sum divisible by K.                          |
| 7  | **Two pairs with sum = target**               | Two nested two-pointer loops              | `[1,2,3,4,5], target=6 → pairs (1,5),(2,4)`                            | Sometimes solved as **two two-pointer pairs**.          |
| 8  | **Four numbers forming rectangle / area**     | Sorting + Four-pointer                    | `[x=[1,2], y=[3,4]] → area=12`                                         | Geometric problems with 4 coordinates.                  |
| 9  | **Four numbers with difference = target**     | Sorting + Four-pointer                    | `[1,2,4,5,6], target=3 → [1,2,4,6]`                                    | Find quadruplet satisfying difference constraints.      |
| 10 | **Longest subarray of size 4 with sum ≤ K**   | Sliding window variant                    | `[1,2,3,4,5], K=10 → [1,2,3,4]`                                        | Fixed-size four-element subarray problem.               |
| 11 | **Quadruplet forming arithmetic progression** | Sorting + Four-pointer                    | `[1,2,3,4,5,6] → [1,2,3,4],[2,3,4,5]`                                  | Find quadruplets where difference is constant.          |
| 12 | **4Sum smaller than target**                  | Four-pointer                              | `[1,2,3,4,5], target=10 → count=4`                                     | Count quadruplets with sum < target.                    |
