| System                          | Patterns                         | Key Concepts                                        | LLD Focus                                                     | Example Scenario                                |
| ------------------------------- | -------------------------------- | --------------------------------------------------- | ------------------------------------------------------------- | ----------------------------------------------- |
| Notification System             | Observer + Strategy + Factory    | Subscribers, channels, notification manager         | Broadcast notifications via multiple channels dynamically     | Send order/shipping alerts via email, SMS, push |
| Rate Limiter                    | Strategy + Singleton + Redis     | Sliding/fixed window, Redis counter, API middleware | Control API usage, distributed-safe                           | Limit API calls per user/IP                     |
| Kafka Event System              | Factory + DI + Pub/Sub           | Producer, Consumer, Event, Kafka topic              | Decoupled event-driven communication, scalable and extendable | Event-driven order processing                   |
| Payment Gateway                 | Strategy + Factory + Adapter     | Payment methods, gateways, adapters                 | Integrate multiple payment providers with same interface      | Integrate Stripe, PayPal, Razorpay              |
| Chat Messaging System           | Observer + Strategy + Queue      | Users, messages, delivery strategies                | Real-time messaging with multiple delivery strategies         | WhatsApp-style chat system                      |
| E-commerce Cart                 | Singleton + Strategy             | Cart instance, discount strategies                  | Single cart per user, apply dynamic discount rules            | User shopping cart management                   |
| File Upload System              | Strategy + Observer              | File handlers, upload events, storage adapters      | Handle multiple file types with pluggable storage backends    | Image/video upload service                      |
| Email Campaign System           | Factory + Observer               | Email templates, subscribers, delivery strategies   | Send personalized campaigns to many users                     | Marketing campaigns                             |
| Logging System                  | Singleton + Strategy             | Log levels, loggers, handlers                       | Centralized logging, dynamic log level handling               | Application-wide logging                        |
| Analytics Event System          | Observer + Pub/Sub               | Event producers, consumers, processing pipelines    | Real-time analytics with decoupled event processing           | Track user clicks and events                    |
| Feature Toggle System           | Strategy + Singleton             | Toggle strategies, feature flags                    | Enable/disable features dynamically across environments       | Rollout new features gradually                  |
| Search Index System             | Factory + Strategy               | Index creators, search strategies                   | Build search indexes dynamically, support multiple strategies | Elasticsearch index creation                    |
| Recommendation Engine           | Strategy + Observer              | User actions, recommendation algorithms             | Generate recommendations based on dynamic user activity       | Amazon/Netflix recommendation system            |
| Rate-based Notifications        | Observer + Strategy + Singleton  | Thresholds, subscriber list, notification triggers  | Notify users based on thresholds and rules dynamically        | Notify user when price drops                    |
| Workflow Orchestration System   | State + Strategy + Observer      | Jobs, pipelines, states                             | Orchestrate multi-step workflows with dynamic state handling  | Order fulfillment workflow                      |
| Microservices API Gateway       | Adapter + DI + Strategy          | Service adapters, routing, authentication           | Route API requests dynamically, adapt to multiple services    | Kong/Nginx API gateway                          |
| Content Management System       | Factory + Strategy + DI          | Pages, components, plugins                          | Dynamically create components and inject dependencies         | WordPress / CMS builder                         |
| Payment Receipt Decorator       | Decorator + Strategy             | Receipt formatting, tax calculations                | Add extra functionality (tax, discount) dynamically           | Add discount/tax to receipts                    |
| Notification Email Decorator    | Decorator + Observer             | Email content, attachments                          | Dynamically extend email notifications without changing core  | Add attachments to notifications                |
| Multi-tenant SaaS Config System | Singleton + DI + Strategy        | Tenant configs, feature strategies                  | Centralized configuration management per tenant               | SaaS multi-tenant feature flags                 |
| Job Scheduler                   | Strategy + State + DI            | Jobs, schedules, retry strategies                   | Dynamically schedule, retry, and manage job execution         | Cron jobs / batch processing                    |
| API Rate Limiter (Advanced)     | Singleton + Strategy + DI        | User limits, service tiers, distributed store       | Extendable, distributed-safe rate limiting                    | Multi-region API throttling                     |
| Cache Management System         | Singleton + Strategy + Decorator | Cache layers, eviction policies                     | Wrap existing services with caching dynamically               | Redis/Memcached cache wrapper                   |
| Payment Fraud Detection         | Strategy + Observer + Factory    | Detection rules, alert strategies                   | Dynamically apply rules to multiple payment events            | Flag fraudulent transactions                    |
| Real-Time Analytics Dashboard   | Observer + Pub/Sub + DI          | Event streams, metric processors                    | Real-time metrics, plug-and-play consumer modules             | Grafana-style dashboards                        |
| User Authentication Service     | Singleton + Strategy + DI        | Tokens, session store, strategy patterns            | Centralized authentication with multiple strategies           | JWT, OAuth login handling                       |
| Email Verification System       | Observer + Strategy + DI         | Verification emails, tokens, retry logic            | Send verification emails and update user state                | User sign-up flow                               |
| Notification Retry System       | Strategy + State + Observer      | Retry queues, backoff strategies                    | Retry failed notifications automatically                      | Retry email/SMS delivery                        |
| Multi-Language Content System   | Strategy + Factory + DI          | Content translators, loaders                        | Dynamically provide content in multiple languages             | i18n / localization                             |
| Document Approval Workflow      | State + Observer + Strategy      | Document states, approval rules                     | Track multi-step approvals for documents                      | Contract approval system                        |
| Metrics Aggregation Service     | Singleton + Observer + Strategy  | Metrics collectors, aggregators                     | Aggregate metrics from multiple sources                       | Prometheus metrics collection                   |
