| #  | Problem                                                     | Type / Technique        | Example                                              | Notes / Use Case                                                      |
| -- | ----------------------------------------------------------- | ----------------------- | ---------------------------------------------------- | --------------------------------------------------------------------- |
| 1  | **3Sum**                                                    | Three-pointer           | `[-1,0,1,2,-1,-4], target=0 → [-1,-1,2], [-1,0,1]`   | Find all triplets with sum = target. Classic LeetCode/FAANG question. |
| 2  | **3Sum Closest**                                            | Three-pointer           | `[-1,2,1,-4], target=1 → sum closest = 2`            | Find triplet sum **closest** to target.                               |
| 3  | **Triplet with smaller sum**                                | Three-pointer           | `[−2,0,1,3], target=2 → count=2 ([−2,0,1],[−2,0,3])` | Count number of triplets less than target.                            |
| 4  | **Triplet product**                                         | Three-pointer           | `[1,2,3,4], target=24 → [2,3,4]`                     | Find triplet with maximum or specific product.                        |
| 5  | **Triplet difference = target**                             | Sorting + Two-pointer   | `[1,2,4,5,6], target=3 → [1,4,6]`                    | Find triplet with difference = target.                                |
| 6  | **Triangle count / Triplet with sum < max**                 | Three-pointer           | `[2,3,4,5], maxSum=10 → count=3`                     | Count number of triplets forming triangle (a+b>c).                    |
| 7  | **Triplet sum in sorted array**                             | Three-pointer           | `[1,2,3,4,5], target=9 → [2,3,4]`                    | Sorted array → standard 3-pointer pattern.                            |
| 8  | **Triplet sum closest to zero**                             | Three-pointer           | `[−1,1,2,−2,3] → closest sum=0`                      | Useful in **finance or zero-balance problems**.                       |
| 9  | **Triplet sum divisible by K**                              | Sorting + Two-pointer   | `[1,2,3,4,5], K=3 → [1,2,3]`                         | Find triplet sum divisible by given number.                           |
| 10 | **Triplet with product divisible by K**                     | Sorting + Modulo        | `[2,3,4,6], K=6 → [2,3,6]`                           | Product-based triplet problem.                                        |
| 11 | **Triplet with sum in range [L,R]**                         | Three-pointer           | `[1,2,3,4], range=[5,7] → [1,2,3],[1,2,4],[1,3,4]`   | Count number of triplets in sum range.                                |
| 12 | **Triplet with sum closest to target (duplicates allowed)** | Three-pointer + HashSet | `[1,1,2,2,3], target=6 → [1,2,3]`                    | Variation where duplicates are allowed, return any triplet.           |
| 13 | **Triplet with two elements equal**                         | Sorting + Two-pointer   | `[1,1,2,2,3], target=4 → [1,1,2]`                    | Triplet with exactly two same numbers.                                |
| 14 | **Triplet in unsorted array**                               | Hashing                 | `[3,7,1,2,8], target=12 → [3,1,8]`                   | Use HashMap for O(n²) without sorting.                                |
| 15 | **Triplet forming arithmetic progression**                  | Sorting + Three-pointer | `[1,3,5,7] → [1,3,5],[3,5,7]`                        | Find triplet where nums[j]-nums[i] = nums[k]-nums[j]                  |
